<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TwdSaveEditor.Core\TwdSaveEditor.Core.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Core.Binary\TwdSaveEditor.Core.Binary.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.Common\TwdSaveEditor.Season.Common.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.Michonne\TwdSaveEditor.Season.Michonne.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.S1\TwdSaveEditor.Season.S1.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.S2\TwdSaveEditor.Season.S2.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.S3\TwdSaveEditor.Season.S3.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.S4\TwdSaveEditor.Season.S4.csproj" />
    </ItemGroup>

</Project>
