<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Data\*.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TwdSaveEditor.Core\TwdSaveEditor.Core.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.Base\TwdSaveEditor.Season.Base.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.Common\TwdSaveEditor.Season.Common.csproj" />
      <ProjectReference Include="..\TwdSaveEditor.Season.S1\TwdSaveEditor.Season.S1.csproj" />
    </ItemGroup>

</Project>
